import type { Metadata } from "next";
import Document, { Head, Html, Main, NextScript } from "next/document";

// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

class MyDocument extends Document{
  render(){
    return (
      <Html>
        <Head>
        <link rel="icon" type="image/x-icon" href="/icon.ico"></link>
        </Head>
        <body>
          <Main  />
          <NextScript />
        </body>
      </Html>
    )
  }
}
export default MyDocument;